title: Jonathan Jiang
logo: /assets/img/logo.png
description: Showcasing my work in data analytics.
#show_downloads: true
#google_analytics:
author:
  name: Jonathan Jiang
  #email: john@example.com
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
